version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm ci

      - echo "Starting build..."
      - npm run build
      - echo "Build completed successfully"
      - ls -la build/ || echo "ERROR: build directory not found"
artifacts:
  base-directory: build
  files:
    - '**/*'
