version: 0.2

phases:
  install:
    commands:
      - npm install
    pre_build:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'
