version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm ci
      - aws secretsmanager get-secret-value --secret-id youtube-api-key --region ap-northeast-1 --query SecretString --output text > /tmp/api_key.txt
      - export REACT_APP_YOUTUBE_API_KEY=$(cat /tmp/api_key.txt)
  build:
    commands:
      - npm run build
